version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      NODE_ENV: development
      PORT: 3000
    ports:
      - "8080:3000"

  postgres:
    image: postgres:14
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: 6880281
      POSTGRES_DB: test