version: "3.8"

services:
  e2e:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      PORT: 3000
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - .for_test.env

